export const HINTS = [
  {
    id: "tour-no-completado",
    title: "Recorrido guiado disponible",
    description: "Te recomendamos hacer el tour interactivo para conocer todas las funcionalidades de la aplicacion.",
    action: { label: "Iniciar tour", tourId: "onboarding" },
    condition: (ctx) => ctx.currentView === "dashboard" && ctx.tourCompleted === false,
    priority: 100,
  },
  {
    id: "tema-personalizable",
    title: "Personaliza los colores",
    description: "Podes cambiar los colores de la interfaz y de cada estado de caso desde Configuracion.",
    action: { label: "Abrir configuracion", navigateTo: "config" },
    condition: (ctx) => ctx.currentView === "settings" && !ctx.themeCustomConfigured,
    priority: 90,
  },
  {
    id: "filtros-no-usados",
    title: "Filtra tus casos",
    description: "Los filtros por mes y estado te permiten encontrar casos mas rapido y organizar tu trabajo.",
    condition: (ctx) => ctx.currentView === "kanban" && (ctx.stats.filtersUsed || 0) === 0,
    priority: 80,
  },
  {
    id: "mapeo-no-configurado",
    title: "Configura el mapeo de estudios",
    description: "Asigna estudios juridicos a localidades en Utiles → Estudios Juridicos para que se asignen automaticamente.",
    action: { label: "Ir a Estudios Juridicos", navigateTo: "utiles" },
    condition: (ctx) => ctx.currentView === "utiles" && (ctx.stats.mapeoCount || 0) === 0,
    priority: 85,
  },
  {
    id: "speechs-vacios",
    title: "Crea tus primeros speechs",
    description: "Los speechs te ayudan a mantener consistencia en las llamadas. Crealos en Utiles → Speechs.",
    action: { label: "Ir a Speechs", navigateTo: "utiles" },
    condition: (ctx) => ctx.currentView === "utiles" && (ctx.stats.speechsCount || 0) === 0,
    priority: 70,
  },
  {
    id: "dashboard-actividad",
    title: "Haz clic en las barras del grafico",
    description: "Las barras de actividad semanal muestran los casos del dia al hacer clic. Probalo para ver el detalle.",
    condition: (ctx) => ctx.currentView === "dashboard" && ctx.dashboardClicks === 0,
    priority: 60,
  },
  {
    id: "backup-no-configurado",
    title: "Configura backups automaticos",
    description: "Evita perder datos configurando backups automaticos en Configuracion → Automatizacion.",
    action: { label: "Ir a Automatizacion", navigateTo: "config" },
    condition: (ctx) => ctx.currentView === "settings" && !ctx.backupConfigured,
    priority: 75,
  },
  {
    id: "atajos-teclado",
    title: "Usa atajos de teclado",
    description: "Ctrl+N para nuevo caso, Ctrl+R para reporte, Ctrl+K para busqueda global. Ahorran mucho tiempo.",
    condition: (ctx) => (ctx.stats.casosCreados || 0) > 5 && !ctx.usesShortcuts,
    priority: 50,
  },
  {
    id: "notas-vinculadas",
    title: "Vincula notas a casos",
    description: "Podes vincular notas del Bloc de Notas a casos especificos para tener toda la informacion relacionada.",
    condition: (ctx) => (ctx.stats.notasCreadas || 0) > 3 && (ctx.stats.notasVinculadas || 0) === 0,
    priority: 55,
  },
  {
    id: "modo-no-molestar",
    title: "Activa el Modo No Molestar",
    description: "Durante llamadas importantes, activa el Modo No Molestar desde el icono de campana para evitar notificaciones.",
    condition: (ctx) => ctx.currentView === "dashboard" && (ctx.stats.casosLlamados || 0) > 10 && !ctx.usesDND,
    priority: 45,
  },
];
