export const TOURS = {
  onboarding: {
    id: "onboarding",
    label: "Tour completo",
    steps: [
      {
        id: "dashboard",
        selector: '[data-tour="dashboard"]',
        title: "1. Dashboard: panel de control",
        description: "El Dashboard integra todas las metricas de la app en 6 pestanas configurables.",
        details: [
          "Analitica: KPIs, insights, distribucion por estado y categoria, evolucion, caseros por aseguradora/localidad, conversion por estudio y funnel",
          "Resumen: insight vs 30 dias, KPIs con tendencia, funnel, actividad 7 dias, alertas, acciones rapidas, proximos eventos, notas, ultimos casos y Mi Dia",
          "Rendimiento: conversion, tiempo en gestion, tasa de perdida y Logro de Objetivos",
          "Geografia: tabla por provincia/localidad y mapa interactivo",
          "Estudios: desempeno de cada estudio juridico",
          "Estados: distribucion por estado del pipeline",
          "Todo se personaliza en Configuracion → Apariencia → Vistas",
        ],
        tips: "El insight del Resumen compara el periodo actual contra los ultimos 30 dias automaticamente.",
        placement: "bottom",
      },
      {
        id: "kanban",
        selector: '[data-tour="kanban"]',
        title: "2. Tablero Kanban",
        description: "El corazon operativo: casos organizados por estado con arrastrar y soltar.",
        details: [
          "Los 11 estados cubren todo el ciclo: Pendiente, Cita virtual, Cita presencial, No responde, Lo piensa, Reprogramado, Tiene Abogado, No le interesa, No viable, Firmo y Sin reporte",
          "Arrastra tarjetas entre columnas para cambiar el estado al instante",
          "Las tarjetas muestran nombre, telefono, dias en estado, estudio y etiquetas",
          "La Pipeline Bar superior muestra la distribucion y filtra al hacer clic",
          "Respeta el filtro de mes y la busqueda en tiempo real",
        ],
        tips: "Los colores de cada estado se personalizan en Configuracion → Apariencia → Colores.",
        placement: "bottom",
      },
      {
        id: "tabla",
        selector: '[data-tour="tabla"]',
        title: "3. Vista de Tabla",
        description: "Todos los casos en una grilla con columnas a medida.",
        details: [
          "Ordena ascendente o descendente haciendo clic en cualquier encabezado",
          "Seleccion multiple con checkboxes para exportar a CSV o eliminar en lote",
          "Filtros combinados: mes, dia y busqueda por texto",
          "En Configuracion → Columnas muestras u ocultas columnas y restauras las basicas",
        ],
        tips: "El contador de seleccion te indica cuantos casos elegiste para exportar.",
        placement: "bottom",
      },
      {
        id: "reportes",
        selector: '[data-tour="reportes"]',
        title: "4. Vista de Reportes",
        description: "Historial completo de novedades de todos los casos.",
        details: [
          "Cada reporte muestra el caso, la fecha, el estado anterior y el nuevo, y la novedad",
          "Busqueda en vivo por nombre del caso, texto de la novedad o estado",
          "Filtro por mes para acotar el periodo",
          "Los reportes se pueden editar o eliminar desde el detalle del caso",
        ],
        tips: "Cargar reportes con el formato (DD/MM)Texto registra varias novedades separadas por //.",
        placement: "bottom",
      },
      {
        id: "utiles",
        selector: '[data-tour="utiles"]',
        title: "5. Utiles: caja de herramientas",
        description: "Recursos practicos para atender prospectos y organizar tu trabajo.",
        details: [
          "Pasos a Seguir: protocolo de atencion paso a paso",
          "Speechs: guiones con copia al portapapeles para llamadas",
          "Objeciones: respuestas categorizadas para objeciones comunes",
          "Conversaciones Sugeridas: plantillas de 3 etapas con {OPERADOR}",
          "Aseguradoras (ART y Transito), Lesiones y Estudios Juridicos con mapeo",
          "Tips y Links utiles de referencia",
        ],
        tips: "El mapeo de localidades a estudios asigna el estudio automaticamente al crear un caso.",
        placement: "bottom",
      },
      {
        id: "mi-espacio",
        selector: '[data-tour="mi-espacio"]',
        title: "6. Mi Espacio: tu centro personal",
        description: "Perfil, jornada, disponibilidad, metas y accesos del operador, todo local.",
        details: [
          "Perfil: nombre, rol, empresa, jornada habitual y dias laborables",
          "Resumen de la jornada: estado del dia, progreso de metas y ritmo necesario",
          "Disponibilidad: vacaciones, feriados, inasistencias y dias no laborables",
          "Metas: objetivo diario y mensual de casos y reportes sobre dias efectivos",
          "Accesos: credenciales personales que nunca se exportan",
          "Las sugerencias inteligentes te avisan cuando falta poco para cumplir tus metas",
        ],
        tips: "Configura tu disponibilidad y el calendario la mostrara automaticamente.",
        placement: "bottom",
      },
      {
        id: "buscar",
        selector: '[data-tour="buscar"]',
        title: "7. Busqueda de casos",
        description: "Busqueda en tiempo real con soporte para etiquetas y comentarios.",
        details: [
          "Escribe nombre, telefono o localidad y filtra al instante",
          "#etiqueta busca casos con esa etiqueta (ej: #urgente)",
          "@texto busca casos cuyo comentario empieza con ese texto",
          "La busqueda funciona en todas las vistas",
        ],
        tips: "Ctrl+F enfoca este campo y Ctrl+K abre la Busqueda Global en casos, notas y eventos.",
        placement: "bottom",
      },
      {
        id: "nuevo-caso",
        selector: '[data-tour="nuevo-caso"]',
        title: "8. Nuevo caso y ficha completa",
        description: "Carga prospectos de forma manual o pegando una ficha.",
        details: [
          "Completa el formulario o pega una ficha con NOMBRE:, TELEFONO:, LOCALIDAD:, ART:, etc.",
          "La ficha se procesa automaticamente y completa los campos",
          "El nombre se guarda en mayusculas y el telefono debe tener al menos 6 digitos",
          "Puedes agregar etiquetas (tags) y comentarios desde el editor",
        ],
        tips: "Las etiquetas te permiten filtrar y organizar casos similares.",
        placement: "bottom",
      },
      {
        id: "cargar-reporte",
        selector: '[data-tour="cargar-reporte"]',
        title: "9. Cargar reporte rapido",
        description: "Registra novedades sin abrir el detalle del caso.",
        details: [
          "Busca el caso por nombre, telefono o localidad",
          "Selecciona el nuevo estado si corresponde",
          "Escribe la novedad con el formato recomendado (DD/MM)Texto",
          "El reporte se guarda con la fecha y hora actuales",
        ],
        tips: "El cambio de estado se refleja automaticamente en el Kanban.",
        placement: "bottom",
      },
      {
        id: "calendario",
        selector: '[data-tour="calendario"]',
        title: "10. Calendario",
        description: "Gestiona eventos, citas y recordatorios en una vista mensual.",
        details: [
          "Haz clic en un dia para crear un evento con titulo, hora, prioridad y caso vinculado",
          "Los eventos vinculados aparecen en el Dashboard en 'Proximos eventos'",
          "Activa recordatorios para recibir notificaciones cuando llegue la fecha",
          "Los dias con eventos se muestran resaltados",
        ],
        tips: "Puedes crear un evento directamente desde el detalle de un caso.",
        placement: "bottom",
      },
      {
        id: "notas",
        selector: '[data-tour="notas"]',
        title: "11. Bloc de Notas",
        description: "Editor de notas con auto-guardado, etiquetas y vinculacion a casos.",
        details: [
          "Cada nota tiene titulo, contenido con formato, tags y vinculo a casos",
          "El auto-guardado evita perder lo que escribis",
          "Busca por texto o filtra por tags en la barra lateral",
          "Las notas vinculadas a un caso se ven en su detalle",
        ],
        tips: "Las notas se exportan junto a la configuracion en JSON.",
        placement: "bottom",
      },
      {
        id: "configuracion",
        selector: '[data-tour="configuracion"]',
        title: "12. Configuracion",
        description: "Categorias para adaptar la app a tu forma de trabajar.",
        details: [
          "General: operador, formato de fecha/telefono, idioma, sonidos, columnas y datos",
          "Apariencia: temas, colores por estado y vistas del Dashboard",
          "Notificaciones: sonido, tipos de eventos y frecuencia",
          "Busqueda: campos indexados e historial",
          "Sistema: experiencia de usuario, modo bajo consumo y diagnostico",
          "Avanzado: dashboard, estados de caso, tipos de ingreso e importacion",
        ],
        tips: "Todo se guarda automaticamente. Exporta tu configuracion para compartirla con otros operadores.",
        placement: "bottom",
      },
      {
        id: "modo-no-molestar",
        selector: '[data-tour="modo-no-molestar"]',
        title: "13. Notificaciones y No Molestar",
        description: "Controla como y cuando te llegan los avisos.",
        details: [
          "Todas las notificaciones se muestran como toasts dentro de la app",
          "Configura el sonido y el volumen desde Configuracion → Notificaciones",
          "Agrupa las notificaciones cada 5, 15, 30 minutos o 1 hora",
          "El Modo No Molestar silencia todo de un solo toque",
        ],
        tips: "No se usan notificaciones del navegador: todo llega como toast in-app.",
        placement: "bottom",
      },
      {
        id: "ayuda",
        selector: '[data-tour="ayuda"]',
        title: "14. Ayuda y documentacion",
        description: "Todo el material de apoyo en un solo lugar.",
        details: [
          "Acerca de Vistas: explicacion completa de cada pantalla",
          "FAQ, Glosario y Guia de Usuario actualizados",
          "Guia PDF: imprime o descarga la guia completa en TXT",
          "Documentacion: README y CHANGELOG",
        ],
        tips: "Ctrl+H abre la Ayuda desde cualquier pantalla.",
        placement: "bottom",
      },
      {
        id: "herramientas",
        selector: '[data-tour="herramientas"]',
        title: "15. Herramientas del caso",
        description: "Desde el modal de un caso, accede a condicionales, speechs, objeciones, notas y eventos vinculados.",
        details: [
          "Condicionales y speechs relacionados con la ART/estudio del caso",
          "Crear nota o evento vinculado directamente desde aqui",
          "Ver notas y eventos vinculados al caso",
          "Ir a Notas o Calendario manteniendo el contexto",
        ],
        tips: "El titulo del caso es clickable: busca en Prolegal.",
        placement: "left",
      },
      {
        id: "citas-config",
        selector: '[data-tour="citas-config"]',
        title: "16. Configuracion de Citas",
        description: "Configura como el sistema gestiona citas automaticas, reprogramaciones y eventos vinculados.",
        details: [
          "Crear eventos automaticamente desde el campo CITA",
          "Actualizar eventos al modificar CITA",
          "Crear nueva cita al usar 'Reprogramado'",
          "Mostrar informacion del caso en eventos vinculados",
        ],
        tips: "Estas opciones estan en Configuracion → General → Citas y Calendario.",
        placement: "right",
      },
      {
        id: "reprogramacion",
        selector: '[data-tour="reprogramacion"]',
        title: "17. Reprogramaciones",
        description: "Cuando un reporte cambia a 'Reprogramado', se crea un nuevo evento de cita conservando el original.",
        details: [
          "Ingresa la nueva fecha y horario de la cita",
          "Se crea un evento de reprogramacion vinculado al caso y reporte",
          "El evento original se conserva como cancelado",
          "La reprogramacion aparece en Calendario, Dashboard e Historial",
        ],
        tips: "Las reprogramaciones se cuentan en el Dashboard.",
        placement: "left",
      },
    ],
  },
};
