export const GLOSSARY_TERMS = [
  {
    term: "ART",
    definition: "Aseguradora de Riesgos del Trabajo. Empresa que cubre accidentes y enfermedades laborales de los trabajadores en relacion de dependencia.",
    example: "Ej: Sancor Salud, Galeno ART, OMINT ART",
    related: ["Aseguradora", "Accidente laboral"],
  },
  {
    term: "Derivacion",
    definition: "Proceso de enviar un caso al estudio juridico correspondiente segun la localidad del accidente o enfermedad laboral.",
    example: "Ej: Un caso de CABA se deriva a un estudio juridico de CABA",
    related: ["Estudio Juridico", "Mapeo"],
  },
  {
    term: "Caso",
    definition: "Registro completo de un prospecto que incluye datos personales, informacion del accidente, estado actual, historial de reportes y configuracion de seguimiento.",
    example: "Ej: Juan Perez - Fractura de brazo - Estado: Cita virtual",
    related: ["Prospecto", "Reporte", "Estado del caso"],
  },
  {
    term: "Prospecto",
    definition: "Persona que ha sufrido un accidente o enfermedad laboral y esta siendo evaluada para una derivacion a estudio juridico.",
    example: "Ej: Trabajador que llamo por un accidente laboral",
    related: ["Caso", "Derivacion"],
  },
  {
    term: "Operador",
    definition: "Usuario de la aplicacion que gestiona los casos, realiza llamadas, registra reportes y da seguimiento a los prospectos.",
    example: "Ej: Tu nombre configurado en Ajustes Generales",
    related: ["Configuracion"],
  },
  {
    term: "Estado del caso",
    definition: "Indicador de la etapa actual del proceso de derivacion. Los estados posibles son: Cita virtual, Cita presencial, No responde, Lo piensa, Reprogramado, Tiene Abogado, No le interesa, No viable, Pendiente, Firmo, Sin reporte.",
    example: "Ej: Cambiar de 'Cita virtual' a 'Firmo' cuando se concreta",
    related: ["Kanban", "Pipeline"],
  },
  {
    term: "Firma",
    definition: "Estado final exitoso que indica que el prospecto firmo el acuerdo con el estudio juridico. Es el objetivo principal del seguimiento.",
    example: "Ej: 'Firmo' = Caso cerrado con exito",
    related: ["Estado del caso", "Objetivo"],
  },
  {
    term: "Cita virtual",
    definition: "Cita agendada por telefono o videollamada con el prospecto para evaluar su caso y explicar el proceso de derivacion.",
    example: "Ej: Llamada programada para el 20/07 a las 10:00",
    related: ["Cita presencial", "Estado del caso"],
  },
  {
    term: "Cita presencial",
    definition: "Cita agendada para una reunion fisica entre el prospecto y el operador o estudio juridico.",
    example: "Ej: Reunion en la oficina del estudio juridico",
    related: ["Cita virtual", "Estado del caso"],
  },
  {
    term: "Kanban",
    definition: "Metodo visual de organizacion que usa columnas para representar cada estado del caso. Las tarjetas se arrastran entre columnas para actualizar el estado.",
    example: "Ej: Arrastrar una tarjeta de 'Cita virtual' a 'Firmo'",
    related: ["Estado del caso", "Pipeline"],
  },
  {
    term: "Pipeline",
    definition: "Barra de progreso que muestra la distribucion de casos en cada estado del proceso, permitiendo ver de un vistazo el flujo de trabajo.",
    example: "Ej: Barra horizontal en el Tablero Kanban",
    related: ["Kanban", "Estado del caso"],
  },
  {
    term: "Reporte",
    definition: "Registro de una novedad o seguimiento en un caso. Cada reporte incluye fecha, texto y opcionalmente un cambio de estado.",
    example: "Ej: '20/07 - Se contacto al prospecto, agendo cita virtual'",
    related: ["Caso", "Historial"],
  },
  {
    term: "Speech",
    definition: "Guion o frase predefinida utilizada durante las llamadas telefonicas para mantener consistencia en la comunicacion con los prospectos.",
    example: "Ej: 'Hola, soy {OPERADOR} de la linea informativa...'",
    related: ["Utiles", "Objecion"],
  },
  {
    term: "Objecion",
    definition: "Respuesta o argumento que un prospecto puede dar para rechazar o dudar del servicio. La app permite registrar y gestionar respuestas para objeciones comunes.",
    example: "Ej: 'No me interesa', 'Ya tengo abogado', 'Es muy caro'",
    related: ["Speech", "Utiles"],
  },
  {
    term: "Lesion",
    definition: "Daño fisico o enfermedad sufrida por el trabajador a causa de su actividad laboral. Se categoriza por tipo en la seccion Utiles.",
    example: "Ej: Fractura, lesion de columna, traumatismo craneal",
    related: ["Caso", "Accidente laboral"],
  },
  {
    term: "Aseguradora",
    definition: "Entidad que brinda cobertura ante riesgos laborales. En la app se administran ART y aseguradoras de transito.",
    example: "Ej: Sancor Salud, Galeno ART, Federacion Patronal",
    related: ["ART", "Transito"],
  },
  {
    term: "Estudio Juridico",
    definition: "Bufete de abogados que se encarga de la representacion legal del trabajador. Se mapean por localidad en Utiles.",
    example: "Ej: Estudio Perez & Asociados - Responsable: Dr. Perez",
    related: ["Derivacion", "Mapeo"],
  },
  {
    term: "Mapeo",
    definition: "Configuracion que asigna estudios juridicos a localidades especificas. Al crear un caso, se asigna automaticamente el estudio segun la localidad.",
    example: "Ej: San Miguel de Tucuman → Estudio Lopez",
    related: ["Estudio Juridico", "Derivacion"],
  },
  {
    term: "Etiqueta",
    definition: "Palabra clave que se asigna a un caso para categorizarlo y facilitar su busqueda y filtrado. Se buscan escribiendo #etiqueta en el campo de busqueda.",
    example: "Ej: 'Urgente', 'Seguro', 'Prioridad Alta' - buscar con #urgente",
    related: ["Caso", "Busqueda"],
  },
  {
    term: "Bloc de Notas",
    definition: "Herramienta para crear y gestionar notas personales con editor de texto, etiquetas y vinculacion a casos. Accesible desde el header.",
    example: "Ej: Nota con observaciones sobre un caso especifico",
    related: ["Caso", "Nota"],
  },
  {
    term: "Dashboard",
    definition: "Panel de control principal con 6 pestanas (Analitica, Resumen, Rendimiento, Geografia, Estudios y Estados) que integran KPIs con tendencia, funnel de conversion, alertas automaticas, actividad semanal, mapa de casos y desempeno de estudios. Las pestanas, widgets y metricas son configurables.",
    example: "Ej: Pestana Resumen con KPIs, funnel y proximos eventos",
    related: ["KPI", "Funnel", "Estadisticas"],
  },
  {
    term: "KPI",
    definition: "Indicador clave de rendimiento. En el Dashboard se muestran: Total casos, Activos, Firmados, Sin reporte y No viables.",
    example: "Ej: Tarjeta 'Firmados: 8' muestra las firmas del mes",
    related: ["Dashboard", "Estadisticas"],
  },
  {
    term: "Modo No Molestar",
    definition: "Funcion que silencia todas las notificaciones de la aplicacion. Se activa desde el icono de campana en el header.",
    example: "Ej: Activar durante una llamada importante para evitar distracciones",
    related: ["Notificaciones", "Configuracion"],
  },
  {
    term: "Overlay",
    definition: "Panel que cubre toda la pantalla para mostrar contenido (Configuracion, Ayuda, Calendario, Bloc de Notas) sin cambiar de vista principal.",
    example: "Ej: Hacer clic en el icono de Configuracion abre un overlay",
    related: ["Modal", "UX"],
  },
  {
    term: "LocalStorage",
    definition: "Almacenamiento local del navegador donde se guarda la configuracion de la app (tema, preferencias, datos de utiles).",
    example: "Ej: El tema oscuro se guarda en LocalStorage",
    related: ["IndexedDB", "Backup"],
  },
  {
    term: "IndexedDB",
    definition: "Base de datos local del navegador utilizada para almacenar los casos, notas y eventos. Mas rapida y con mayor capacidad que LocalStorage.",
    example: "Ej: Los casos se almacenan en IndexedDB via Dexie.js",
    related: ["LocalStorage", "Dexie"],
  },
  {
    term: "Tour interactivo",
    definition: "Recorrido guiado paso a paso por todas las funcionalidades de la aplicacion (13 pasos): Dashboard con sus 6 pestanas, Tablero, Tabla, Reportes, Utiles, Busqueda, Nuevo Caso, Carga de reporte, Calendario, Bloc de Notas, Configuracion, Notificaciones y Ayuda. Se accede desde Ayuda → Tour interactivo y se muestra automaticamente la primera vez.",
    example: "Ej: El Tour interactivo recorre las 6 pestanas del Dashboard",
    related: ["Ayuda", "Onboarding"],
  },
  {
    term: "Autodiagnostico",
    definition: "Sistema de monitoreo que registra errores y permite diagnosticar problemas tecnicos en la aplicacion. Accesible desde Configuracion → Diagnostico.",
    example: "Ej: Muestra el estado de IndexedDB, localStorage y modo offline",
    related: ["Diagnostico", "Configuracion"],
  },
  {
    term: "Conversacion Sugerida",
    definition: "Plantilla de mensaje predefinida con la variable {OPERADOR} que se reemplaza automaticamente con el nombre del operador configurado.",
    example: "Ej: 'Hola, soy {OPERADOR} de la linea de seguimiento...'",
    related: ["Speech", "Operador"],
  },
  {
    term: "Funnel de conversion",
    definition: "Grafico que muestra el recorrido de los casos a traves de las etapas clave del proceso, permitiendo ver cuantos casos pasan de una etapa a la siguiente y donde se pierde conversion.",
    example: "Ej: 100 casos cargados → 40 con cita → 14 firmas",
    related: ["Dashboard", "Conversion"],
  },
  {
    term: "Insight",
    definition: "Mensaje automatico que compara el periodo actual contra los ultimos 30 dias y destaca variaciones relevantes en el Dashboard (ej: las firmas subieron 20%).",
    example: "Ej: 'Las firmas del mes subieron un 20% vs los ultimos 30 dias'",
    related: ["Dashboard", "Analitica"],
  },
  {
    term: "Alerta automatica",
    definition: "Aviso generado por el Dashboard cuando detecta una condicion anormal segun reglas configurables (baja conversion, muchos pendientes, casos sin reporte). Se definen en Configuracion → Apariencia → Dashboard.",
    example: "Ej: Alerta cuando la tasa de conversion baja del 15%",
    related: ["Dashboard", "Notificaciones"],
  },
  {
    term: "Busqueda Global",
    definition: "Paleta de busqueda (Ctrl+K) que busca simultaneamente en casos, notas y eventos. Soporta operadores #etiqueta y @comentario.",
    example: "Ej: Escribir #urgente para ver todo lo etiquetado",
    related: ["Busqueda", "Etiqueta"],
  },
  {
    term: "Importacion (CSV)",
    definition: "Proceso de cargar casos en lote desde un archivo CSV. Incluye mapeo automatico de columnas, vista previa paginada, reparacion de columnas desalineadas y validacion de duplicados.",
    example: "Ej: Importar 50 casos desde un archivo Excel exportado a CSV",
    related: ["Caso", "Exportacion", "Vista previa"],
  },
  {
    term: "Vista previa",
    definition: "Tabla que se muestra antes de importar un CSV con el resultado del mapeo de campos, para verificar los datos antes de confirmar la importacion.",
    example: "Ej: Revisar como quedan los campos antes de importar 50 casos",
    related: ["Importacion", "CSV"],
  },
  {
    term: "Metricas configurables",
    definition: "Los KPIs, widgets y pestanas del Dashboard pueden mostrarse u ocultarse y reordenarse desde Configuracion → Apariencia → Dashboard.",
    example: "Ej: Ocultar la tarjeta de 'No viables' si no la usas",
    related: ["Dashboard", "Configuracion"],
  },
  {
    term: "Reprogramacion",
    definition: "Evento que se crea cuando un reporte cambia el estado del caso a 'Reprogramado'. Registra la nueva fecha y horario de la cita, conservando la original como cancelada.",
    example: "Ej: Caso reprogramado del 15/09 al 20/09 con nuevo horario",
    related: ["Cita", "Reporte", "Caso"],
  },
  {
    term: "Cita automatica",
    definition: "Evento de calendario que se crea o actualiza automaticamente cuando el campo CITA de un caso contiene una fecha y horario en formato DD/MM - (HH:MM a HH:MM).",
    example: "Ej: 15/09 - (14:00 a 15:30) genera un evento vinculado al caso",
    related: ["Calendario", "Caso", "Evento"],
  },
  {
    term: "Evento vinculado",
    definition: "Evento de calendario que esta asociado a un caso a traves del campo relatedCaseIds. Puede ser una cita automatica, un evento manual o una reprogramacion.",
    example: "Ej: Evento 'Cita: Juan Perez' vinculado al caso de Juan Perez",
    related: ["Calendario", "Caso", "Cita"],
  },
  {
    term: "Nota vinculada",
    definition: "Nota del bloc de notas que esta asociada a un caso a traves del campo relatedCaseIds. Permite mantener el contexto del caso al editar la nota.",
    example: "Ej: Nota 'Llamar para confirmar' vinculada al caso de Juan Perez",
    related: ["Nota", "Caso", "Bloc de Notas"],
  },
  {
    term: "Mi Jornada",
    definition: "Seccion de Mi Espacio que muestra el estado de la jornada laboral, tiempo transcurrido, tiempo restante, proximos compromisos y objetivos diarios.",
    example: "Ej: Jornada activa desde las 9:00, 3 horas restantes, 2 casos pendientes",
    related: ["Mi Espacio", "Objetivos", "Disponibilidad"],
  },
];
